SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, I.GENDER, COUNT(DISTINCT I.USER_ID) AS USERS
FROM ONLINE_SALE S
 
LEFT JOIN USER_INFO I
ON S.USER_ID = I.USER_ID

WHERE I.GENDER IS NOT NULL

GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), I.GENDER
ORDER BY YEAR, MONTH, I.GENDER

