 # 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력 / 엔드데이트가 2022년 11월 1일 이전이거나 시작데이트가 2022년 11월 30일 이후
 
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (1-P.DISCOUNT_RATE*0.01)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C

LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID

LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON P.CAR_TYPE = C.CAR_TYPE

WHERE P.DURATION_TYPE = '30일 이상'
AND C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
    WHERE H2.START_DATE <= '2022-11-30' AND H2.END_DATE >= '2022-11-01'
)
HAVING FEE >=500000 AND FEE <2000000

ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC