#자동차 ID, 자동차 종류, 대여 금액(FEE)
#대여금액 기준 내림차순, 자동차 종류 기준 오름차순, 자동차 ID기준 내림차순
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE * 30 * (1-P.DISCOUNT_RATE*0.01))  AS FEE
FROM CAR_RENTAL_COMPANY_CAR C

LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID

LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE

WHERE C.CAR_TYPE IN ('세단', 'SUV')

AND P.DURATION_TYPE = '30일 이상'

AND C.CAR_ID NOT IN(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
    WHERE H2.START_DATE <= '2022-11-30' AND H2.END_DATE >= '2022-11-01'
)

HAVING FEE >= 500000 AND FEE < 2000000

ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC

