# 2022년 3월의 오프라인/온라인 상품 판매 데이터의 판매 날짜, 상품ID, 유저ID, 판매량을 출력하는 SQL
SELECT DATE_FORMAT(N.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, N.PRODUCT_ID, N.USER_ID, N.SALES_AMOUNT
FROM ONLINE_SALE N
WHERE MONTH(N.SALES_DATE) = '3'
UNION
SELECT DATE_FORMAT(F.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, F.PRODUCT_ID, NULL AS USER_ID, F.SALES_AMOUNT
FROM OFFLINE_SALE F 
WHERE MONTH(F.SALES_DATE) = '3'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID