# 2021년에 가입한 회원들 중 상품을 구매한 회원수, 상품을 구매한 회원의 비율(소수 둘째까지 반올림)을 연 월로
# 년 오름차순, 월 오름차순

SELECT YEAR(S.SALES_DATE) AS YEAR, 
MONTH(S.SALES_DATE) AS MONTH, 
COUNT(DISTINCT I.USER_ID) AS PUCHASED_USERS, 
ROUND(COUNT(DISTINCT I.USER_ID) / 
      (SELECT COUNT(I2.USER_ID)
      FROM USER_INFO I2
      WHERE YEAR(I2.JOINED) = '2021')
      ,1) AS PUCHASED_RATIO


FROM ONLINE_SALE S

LEFT JOIN USER_INFO I
ON S.USER_ID = I.USER_ID

WHERE YEAR(I.JOINED) = '2021'

GROUP BY YEAR, MONTH

ORDER BY YEAR, MONTH

