-- 코드를 입력하세요
SELECT F.FLAVOR 
FROM FIRST_HALF F
WHERE F.TOTAL_ORDER > 3000 
AND F.FLAVOR IN (
    SELECT I.FLAVOR
    FROM ICECREAM_INFO I
    WHERE INGREDIENT_TYPE = 'fruit_based'
    )
ORDER BY F.TOTAL_ORDER DESC


