# 들어올 당시에는 중성화 되지 않았지만 보호소 나갈 때는 중성화된 동물 구하기
# 아이디, 생물종, 이름 / 아이디 오름차순

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I

LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID

WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' 
AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')

ORDER BY I.ANIMAL_ID