SELECT MONTH(H2.START_DATE) AS MONTH, H2.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
WHERE H2.CAR_ID IN(
    SELECT H.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY H.CAR_ID
    HAVING COUNT(*) >= 5
) AND (H2.START_DATE BETWEEN '2022-08-01' AND '2022-10-31')

GROUP BY MONTH, H2.CAR_ID

ORDER BY MONTH, H2.CAR_ID DESC








