# 조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로 조회 / FILD ID 내림차순

SELECT CONCAT("/home/grep/src/", B.BOARD_ID, "/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE F

LEFT JOIN USED_GOODS_BOARD B
ON B.BOARD_ID = F.BOARD_ID

WHERE B.VIEWS = 
    (
    SELECT MAX(B2.VIEWS)
    FROM USED_GOODS_BOARD B2
    )

ORDER BY F.FILE_ID DESC