WITH RECURSIVE TIME AS(
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1
    FROM TIME
    WHERE NUM < 23
)

SELECT TIME.NUM, IFNULL(A.COUNT, 0)
FROM TIME
LEFT JOIN (
    SELECT HOUR(O.DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS O
    GROUP BY HOUR(DATETIME)
    ORDER BY HOUR(DATETIME)
) A
ON TIME.NUM = A.HOUR
