#7월 아이스크림 총 주문량+상반기 아이스크림 총 주문량이 큰 순서대로 3개 맛 조회
SELECT H.FLAVOR
FROM FIRST_HALF H

LEFT JOIN

(SELECT J.SHIPMENT_ID, J.FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
FROM JULY J
GROUP BY J.FLAVOR) JJ

ON H.FLAVOR = JJ.FLAVOR

ORDER BY (H.TOTAL_ORDER + TOTAL) DESC
LIMIT 3

