SELECT P2.CATEGORY, MAX(P2.PRICE) AS 'MAX_PRICE', P2.PRODUCT_NAME
FROM FOOD_PRODUCT P2
WHERE (P2.CATEGORY, P2.PRICE) IN ( 
    SELECT P.CATEGORY, MAX(P.PRICE)
    FROM FOOD_PRODUCT P
    GROUP BY P.CATEGORY
)
AND P2.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY P2.CATEGORY

ORDER BY P2.PRICE DESC
