

SELECT P.MEMBER_NAME, N.REVIEW_TEXT, DATE_FORMAT(N.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE P
RIGHT JOIN(
    SELECT *
    FROM REST_REVIEW R2
    WHERE R2.MEMBER_ID IN (
        SELECT R1.MEMBER_ID
        FROM REST_REVIEW R1
        GROUP BY R1.MEMBER_ID
        HAVING COUNT(R1.MEMBER_ID) = (
            SELECT COUNT(R.MEMBER_ID)
            FROM REST_REVIEW R
            GROUP BY R.MEMBER_ID
            ORDER BY COUNT(R.MEMBER_ID) DESC
            LIMIT 1
        )
    )
) N
ON N.MEMBER_ID = P.MEMBER_ID
ORDER BY REVIEW_DATE, N.REVIEW_TEXT 
