# SELECT B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
# FROM BOOK_SALES S
# INNER JOIN BOOK B
# ON B.BOOK_ID = S.BOOK_ID
# GROUP BY B.CATEGORY

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES S
INNER JOIN BOOK B
ON B.BOOK_ID = S.BOOK_ID
INNER JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = '2022' AND MONTH(S.SALES_DATE) = '1'
GROUP BY B.CATEGORY, A.AUTHOR_ID
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC