# 2022년 1월 도서 판매 데이터 기준 저자 별, 카테고리 별 매출액 구하기
# 저자id, 저자명, 카테고리, 매출액 / 저자 ID 오름차순 , 카테고리 내림차순


SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES  * B.PRICE)  AS TOTAL_SALES
FROM BOOK_SALES S

LEFT JOIN BOOK B
ON S.BOOK_ID = B.BOOK_ID

LEFT JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID

WHERE YEAR(S.SALES_DATE) = '2022' AND MONTH(S.SALES_DATE) = '1'

GROUP BY A.AUTHOR_ID, B.CATEGORY

ORDER BY A.AUTHOR_ID, B.CATEGORY DESC