#상품코드 별 매출액 합계 출력 / 매출액 내림차순, 상품코드 오름차순
SELECT P.PRODUCT_CODE, P.PRICE * SUM(SALES_AMOUNT) AS SALES
FROM PRODUCT P

LEFT JOIN OFFLINE_SALE S
ON P.PRODUCT_ID = S.PRODUCT_ID

GROUP BY P.PRODUCT_ID
HAVING SALES IS NOT NULL


ORDER BY SALES DESC, P.PRODUCT_CODE