SELECT DISTINCT H.CAR_ID, '대여중' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE '2022-10-16' BETWEEN H.START_DATE AND H.END_DATE
UNION ALL
SELECT DISTINCT H2.CAR_ID, '대여 가능' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
WHERE H2.CAR_ID NOT IN(
SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE '2022-10-16' BETWEEN H.START_DATE AND H.END_DATE
)
ORDER BY 1 DESC

