# 자동차 종류가 트럭인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액 구하기
# 대여 기록 id, 대여 금액 출력 / 대여 금액 내림차순, 대여 기록 id 내림차순

SELECT DISTINCT H.HISTORY_ID, ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE)+1) * 
    CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 90
        THEN 0.85
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 30
        THEN 0.92
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 7
        THEN 0.95
        ELSE 1
    END, 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H

LEFT JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID

LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE

WHERE C.CAR_TYPE = '트럭'

ORDER BY FEE DESC, H.HISTORY_ID DESC

