# 생산일자가 2022년 5월인 식품의 식품ID, 식품이름, 총매출 /// 총매출 내림차순, 식품ID 오름차순
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P

LEFT JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID

WHERE O.PRODUCE_DATE >= '2022-05-01' AND O.PRODUCE_DATE <= '2022-05-31'

GROUP BY P.PRODUCT_ID

ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID
