# 2022년 4월 13일 취소되지 않은 흉부외과 진료 예약 내역 조회
# 진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시 / 진료예약일시 오름차순

SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A

LEFT JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID

LEFT JOIN PATIENT P
ON A.PT_NO = P.PT_NO

WHERE A.APNT_CNCL_YN = 'N'
AND YEAR(A.APNT_YMD) = '2022' AND MONTH(A.APNT_YMD) = '4' AND DAY(A.APNT_YMD) = '13'
AND D.MCDP_CD = 'CS'

ORDER BY A.APNT_YMD