#경제카테고리에있는 BOOK_ID, 저자명, 출판일//// 결과는 출판일 오름차순
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B

LEFT JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID

WHERE B.CATEGORY IN ('경제')

ORDER BY B.PUBLISHED_DATE